plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-common:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-gui:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-lib:${jei_version}"
    compileOnlyApi "fuzs.forgeconfigapiport:forgeconfigapiport-common:${forge_config_api_port_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.2'
}

dependencies {
    testImplementation sourceSets.main.output
    testCompileOnly files(sourceSets.main.compileClasspath)
    testRuntimeOnly files(sourceSets.main.runtimeClasspath)
    testRuntimeOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    testRuntimeOnly "mezz.jei:jei-${minecraft_version}-common:${jei_version}"
    testRuntimeOnly "mezz.jei:jei-${minecraft_version}-gui:${jei_version}"
    testRuntimeOnly "mezz.jei:jei-${minecraft_version}-lib:${jei_version}"
}

test {
    useJUnitPlatform()
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
repositories {
    maven {
        name = 'Fuzs Mod Resources'
        url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/'
    }
}